import 'package:flutter/widgets.dart';

class InterfaceIcons {
  InterfaceIcons._();

  static const _kFontFam = 'Interface';
  static const _kFontPackage = 'flutter_ui_icons';

  static const IconData add_user =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData alarm_1 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData alarm =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData align_left =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData align_right =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bar_chart =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData binoculars =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bluetooth =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData bookmark =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData briefcase =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData broken_link =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData calculator =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData calendar =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cancel =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData car =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData chat =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData check =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData chevron =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData chrome =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData clicker =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData clip =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud_computing_1 =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud_computing =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData copy =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData credit_card =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData compass =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData crop =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cube =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cloud =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cursor =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cut_1 =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData cut =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dashboard =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData diagram =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData diamond =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData disabled =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData diskette =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData dislike =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData down_arrow_1 =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData down_arrow_2 =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData down_arrow =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData download =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData earth_grid =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData edit =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData email_1 =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData email_2 =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData email =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData equalizer =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData eraser =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData expand =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData facebook =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData eye =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData fast_forward =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData file =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData filter =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData firefox =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData flag =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData folder =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData followers =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData headphones =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData heart =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hide =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData highlighter =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData home =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData hourglass =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData idea =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData information =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData instagram =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData joke =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData justify =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData key =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData layout =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData leaf =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData left_arrow_1 =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData left_arrow_2 =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData left_arrow =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData like =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData loading =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData log_in =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData log_out =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData medal =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData megaphone =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData menu_1 =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData menu =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData microphone =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData minimize =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData minus =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData money =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData monitor =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData moon =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData motorcycle =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData move =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData music =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData mute_1 =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData mute =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData open_lock =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData padlock =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData link =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData paint_bucket =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData paste =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pause =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pencil =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData phone_call_1 =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData phone_call_2 =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData phone_call =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData photo_camera =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData picture =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pie_chart =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData piggy_bank =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pin_1 =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData pin =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData play =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData plus =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData power_button =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData printer =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData push_pin =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData puzzle =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData qr_code =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData question =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData refresh =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData remove_user =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData reply_all =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData reply =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData rewind =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData right_arrow_1 =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData right_arrow =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData sad =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData safari =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData scale =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData screenshot =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData settings =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData share =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shield =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shopping_cart =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData shuffle =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData silence =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData smartphone =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData smile_1 =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData smile =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData snowflake =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData star =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData stop =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData straight =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData sun =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData surprise =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData switch_1 =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData switch_icon =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tag =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData target =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData thermometer =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData thunderbolt =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData tools =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData trash_1 =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData trash =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData truck_2 =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData truck =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData twitter =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData umbrella =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData up_arrow_1 =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData up_arrow_2 =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData up_arrow =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData upload =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData usb =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData user_1 =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData user =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData video_camera =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData video =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData volume =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wall_clock =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wifi =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData wind =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPackage);
  static const IconData youtube =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPackage);
}
